### ISSUE TITLE
Patch based repository format

### ISSUE THREAD

**Issue by leroycep** [Geemili/time-tracker#5]
# Current Format

As of `v0.1.1`, `augr` uses a simple format for storing timesheets and syncing data over syncthing.

- Each device reads and writes to a their own file `<device-id>.unknown`
  - Each line contains an event, with a rfc3339 datetime and a set of space separated tags
- All of the other files are read from, but not written to

This simple format allows data to be shared and synced without conflicts arising. However, this format cannot model the following:

- Deletion of an event made by a different device
- Modification of an event made by a different device

To be a useful tool, `augr` must allow corrections to be made to the data.

# Format requirements

A new format should support the following:

- create, editing, and deleting events
- synchronising data over syncthing without creating conflicts

# Format proposal

The new format is based off of the git and pijul distributed version control systems. Each device will have a central `meta/` file that they read and write to. All devices will share an append only `patches/` folder.

```
sync-folder/
	meta/
		laptop.toml
		phone.toml
	patches/
		1220caf81688dd83f19a04d53b02f86032ac242f73ec803cb51c3b30772705b501c9.toml
		12208cd07f3a5ff98f2a78cfc366c13fb123eb8d29c1ca37c79df190425d5b9e424d.toml
```

Each meta file contains a list of patches that it knows about, meaning that it either created the patch, or it has discovered the patch through another device's meta file.

```toml
# meta/<device-id>.toml

# The set of patches that this device knows about
root_patches = [
	"1220caf81688dd83f19a04d53b02f86032ac242f73ec803cb51c3b30772705b501c9",
	"12208cd07f3a5ff98f2a78cfc366c13fb123eb8d29c1ca37c79df190425d5b9e424d",
]
```

Each patch file lists the patches that it depends on and the changes to make to the timesheet.

```toml
# patches/<patch-hash>.toml

# The patches must be applied before this patch. Can be omitted entirely if the
# patch does not depend on any others.
parents = ["12208cd07f3a5ff98f2a78cfc366c13fb123eb8d29c1ca37c79df190425d5b9e424d"]

# An action, like creating, modifying, or deleting an event
[actions.1220449f475c66559505770e97bf6346199b93cb25d0b63e70ab9d0edeeae42a1854]
type = "create_event"
start = 2019-07-20T15:08:35.753524795+00:00
tags = ["augr", "coding"]

[actions.1220dec4786b6a6a805af212141b3d6bc2a6774cb5bf1eee9c00f7e263d8d8061904]
type = "add_tags"
modifying = ["1220ac27e0f2db749eefe8fc555e08aa619a04d3abdb2ff18e9b8bf1dd9293b1e819"]
tags = ["exercise"]
```

Actions and patches are named by their hash. The hash will be a [multihash][], and will default to a sha-2 256bit hash.

[multihash]: https://github.com/multiformats/rust-multihash

---

That's the basics of the idea. Implementing it will require a lot of the specifics to be ironed out, and I'm not sure that this is the best format to use.

Something that should also be noted is that I haven't verified that the model will make everything sync nicely. Depending on how actions are modeled, a user could end up with a lot of sync conflicts, or very few. Actions must be carefully defined so that conflicts are few, and merging is unsurprising.
